- name: Set up UFW firewall
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present
        cache_valid_time: 86400

    - name: Set default incoming policy to deny
      community.general.ufw:
        direction: incoming
        policy: deny

    - name: Set default outgoing policy to allow
      community.general.ufw:
        direction: outgoing
        policy: allow

    - name: Allow SSH (port 22)
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Allow HTTP (port 80)
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Allow HTTPS (port 443)
      community.general.ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Enable UFW
      community.general.ufw:
        state: enabled
